version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  runner-test:
    machine: true
    resource_class: inito/kamal_dev
    steps:
      - run:
          name: List files
          command: ls -la
      - run:
          name: Change directory
          command: cd /home && pwd
      - run:
          name: Show current directory
          command: pwd
      - run:
          name: Echo test
          command: echo "workflow running"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello

  runner-workflow:
    jobs:
      - runner-test
        filters:
            branches:
              only: [runner-testing]
